### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by ihtiht** [qcam/nabo#11]
Hi,

I am a designer who contributes to open source projects. Does your project need a logo or a banner? If you have an idea, you can say it without hesitation.

I will be waiting for feedback...

**Comment by qcam** [comment]
@ihtiht Wow, that will be awesome if you could help ❤️. The name of "Nabo" came from "Nano Blog". What is the design idea you have in mind? Please kindly let me know what you need.

**Comment by ihtiht** [comment]
Here are my designs;

![nabologo](https://user-images.githubusercontent.com/36369736/40566580-0e5172c8-607a-11e8-8f70-fa2cec58f9dc.jpg)

Please tell me if there is anything you want to change.

I also designed a gif banner.

![gif2](https://user-images.githubusercontent.com/36369736/40579547-7048371a-6132-11e8-8a8b-f4dbbc3e2d44.gif)

**Comment by qcam** [comment]
These look awesome 👍! I love the first logo and also the GIF. Thanks so much for the work!

Would you mind opening a PR and update the README with this?

**Comment by ihtiht** [comment]
Yes, I did. I opened a PR. https://github.com/qcam/nabo/pull/12

**Comment by qcam** [comment]
Merged via #12. Thanks again @ihtiht.
