### ISSUE TITLE
Is there a way to recompile the root directory on a live server?

### ISSUE THREAD

**Issue by madasebrof** [qcam/nabo#8]
Great concept!

Only one problem. Seems that the only way to add new posts to a running system is to:

`mix deps.compile nabo --force`

This seems to be the only way to add new posts--to stop the server & `mix deps.compile nabo --force`.

Is this the desired behavior?!? Not sure how one could run this in production if you were intending to add posts.

Okay, re-reading all the docs. It looks like this is the desired behavior--to compile markdown files into macros.

is there a way to recompile the root directory on a live server? How would you integrate this into a live server?

Answering my own question:

```
iex> r MyBlog.BlogRepo
```

Epic. Kinda wacky. 

This means you'd need to make sure you have `iex` access to be able to do a hot-code reload. Just thinking this through...

**Comment by qcam** [comment]
@madasebrof thanks for reaching out!

> This seems to be the only way to add new posts--to stop the server & `mix deps.compile nabo --force`.

Yes this is intended, all posts need to be pre-compiled (and re-pre-compiled) before it can be used/viewed on servers.

> is there a way to recompile the root directory on a live server? How would you integrate this into a live server?

> This means you'd need to make sure you have iex access to be able to do a hot-code reload.

Nabo doesn't support hot-code reload, I didn't take that into consideration when writing code to be honest. `r MyBlog.BlogRepo` would recompile the module so yes, that _might_ work.

Previously I used [Distillery](https://github.com/bitwalker/distillery) to make releases and re-ran the compiled tarball on server for new posts, that worked quite well but making new release every time is somewhat tedious. Now with Heroku I push and the [Elixir buildpack](https://github.com/HashNuke/heroku-buildpack-elixir) will do all the work. You could take a look at [my blog source code](https://github.com/qcam/hqc.io) if interested.

Thanks again for reaching out and reading all the docs. ❤️

**Comment by madasebrof** [comment]
Makes sense. I am using [Nanobox](https://nanobox.io) with their equivalent [Buildpack](https://guides.nanobox.io/elixir/phoenix/) which is similar to Heroku but for all cloud providers. PS it rocks. It will also automatically builds on deploy, so maybe it's fine the way it is!

:smile: 

and the `r MyBlog.BlogRepo` does seem to work like a charm even in a container. (Which makes sense, as that's what Elixir/Erlang was designed to be able to do from day-one!)

Okay, will keep exploring.
